# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - uses: actions/checkout@v2
       with:
        submodules: recursive
     - uses: actions/cache@v2
       id: npm-cache
       with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
     - uses: actions/cache@v2
       id: elm-cache
       with:
        path: ~/.elm
        key: ${{ runner.os }}-elm--home-${{ hashFiles('**/elm.json', 'elm-tooling.json') }}
     - name: Install dependencies
       if: steps.npm-cache.outputs.cache-hit != 'true'
       env:
          NO_ELM_TOOLING_INSTALL: 1
       run: npm ci
     - name: elm-tooling install
       run: npx --no-install elm-tooling install
     - name: Run elm-format
       run: npx --no-install elm-format src/ --yes
     - name: Apply elm-review fixes
       id: elm-review
       run: yes | npx --no-install elm-review --fix-all
       continue-on-error: true
     - uses: peter-evans/create-pull-request@v3
       with:
        commit-message: 'Apply elm-review fixes'
        branch: fixes-${{ steps.extract_branch.outputs.branch }}
        title: "Apply elm-review fixes"
        body: "*This is an automated pull request because elm-review found problems that could be fixed automatically.*"
        reviewers: sparksp
        assignees: sparksp
